In [3]:
print ("Hello World")

Hello World

In [4]:
height = 170
weight = 100
BMI = weight/(height/100)**2
print ( BMI )

34.602076124567475

In [5]:
x=1
y=3
print(x+y)

4

In [6]:
x=1 y=3 print(x+y)

SyntaxError: invalid syntax (2679769748.py, line 1)

In [9]:
revenue=1000
growthrate=20/100
nextyear=revenue*(1+growthrate)
print(nextyear)

1200.0

In [11]:
numbers=[40,50,60,70]
print(numbers)

[40, 50, 60, 70]

In [12]:
print(numbers[1])

50

In [13]:
sum=sum(numbers)
print(sum)

220

In [18]:
numbers.append(100)
numbers.append(190)
print(numbers)

[40, 50, 60, 70, 100, 100, 100, 190, 100, 190, 100, 190]

In [28]:
names=["tim","amy" ,"john"]
for name in names:
    print(name)

tim
amy
john

In [30]:
numbers=[1,2,3]
for x in numbers:
    print(x*x)

1
4
9

In [31]:
numbers=[1,2,3]
for x in numbers:
    print(x)
    print("a")

1
a
2
a
3
a

In [32]:
numbers=[1,2,3]
for x in numbers:
    print(x)
print("a")

1
2
3
a

In [33]:
numbers=[1,2,3]
for x in numbers:
    print(x)
for x in numbers:
    print("a")

1
2
3
a
a
a

In [36]:
scores=[14,67,89,90,24]
for score in scores:
    if score>=60:
        print(score,"pass")
    else:
        print(score,"fail")

14 fail
67 pass
89 pass
90 pass
24 fail

In [38]:
scores=[14,67,89,90,24]
for score in scores:
    if score>=60:
        print(score,"pass")
    if score<70:
        print(score,"fail")

14 fail
67 pass
67 fail
89 pass
90 pass
24 fail

In [39]:
numbers=[1,2,3,4,5]
for number in numbers:
    if number%2==0:
        print(number)

2
4

In [48]:
def Bmi(weight,height):
    return weight/(height)**2
print (Bmi(120,1.9))
x=[(110,2),(60,1.55)]
for (a,b) in x:
    print(Bmi(a,b))

33.2409972299169
27.5
24.97398543184183

In [49]:
x=add(3,5)
print(x)

NameError: name 'add' is not defined

In [53]:
def add(a,b):
    print (a+b)
x=add(3,5)
print(x)

8
None

In [55]:
scores=[23,35,67,89,90]
for i in range(len(scores)):
    print (i,scores[i])

0 23
1 35
2 67
3 89
4 90

In [56]:
for i in range(6):
    print(i)

0
1
2
3
4
5

In [58]:
total=0
for i in range(1,101):
    total=i+total
print(total)

5050

In [59]:
scores=[12,34,56,78,99]
total=0
for i in range(len(scores)):
    total=scores[i]+total
average=total/len(scores)
print(average)

55.8

In [60]:
numbers=[12,34,7,90,2,1]
for i in numbers:
    if i>numbers[0]:
        print(i)

34
90

In [65]:
numbers=[12,34,7,90,2,1]
max=numbers[0]
for i in numbers:
    if i>numbers[0]:
        max=i
print(max)

90

In [66]:
score=69
if score>=60:
    print("pass")

pass

In [67]:
score=92
if score>=90:
    print("A")
elif score>=80:
    print("B")
elif score>=70:
    print("C")
else:
    print("D")

A

In [73]:
scores=[12,34,56,78,90]
count=0
for score in scores:
    if score<60:
        count+=1
print(count)

3

In [76]:
scores=[12,34,56,78,90]
count=0
for score in scores:
    if score<60:
        count=1
print(count)

1

In [80]:
scores = [45, 67, 89, 100, 32, 76]
pas = [ ]
for score in scores:
    if score>=60:
        pas.append(score)
print(pas)

[67, 89, 100, 76]

In [82]:
words=["apple","pine","watermelon","pear"]
love=[]
for fruit in words:
    if len(fruit)>=5:
        love.append(fruit)
print(love)

['apple', 'watermelon']

In [90]:
def average_score(scores):
    total=0
    for score in scores:
        total+=score
    return total/len(scores)
print(average_score([12,34,56,78,90]))

54.0

In [92]:
def sum(n):
    total=0
    for i in range(0,n+1):
        total+=i
    return total
print(sum(100))

5050

In [94]:
def max(setting):
    max_value=setting[0]
    for i in setting:
        if i>setting[0]:
            max_value=i
    return max_value
pp=[1,23,4,56,67,8,99]
print(max(pp))

99

In [95]:
def passing(scores):
    passed=[]
    for i in scores:
        if i>=60:
            passed.append(i)
    return passed
print(passing([12,34,56,78,90]))

[78, 90]

In [96]:
scores={"math":150,"english":145,"chinese":140}
for kid in scores:
    print(kid,scores[kid])

math 150
english 145
chinese 140

In [97]:
setting=[1,1,1,2,3,1,2,3]
count={}
for i in setting:
    if i in count:
        count[i]+=1
    else:
        count[i]=1
print(count)

{1: 4, 2: 2, 3: 2}

In [102]:
def count(setting):
    count={}
    for i in setting:
        if i in count:
            count[i]+=1
        else:
            count[i]=1
    return count
print(count([1,2,3,4,4,5]))

{1: 1, 2: 1, 3: 1, 4: 2, 5: 1}

In [110]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]

In [106]:
%pip install numpy

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.5.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [111]:
import numpy as np

print(np.__version__)

2.5.0

In [114]:
data=np.array([1,23,424,5,8])
print(np.sum(data))

461

In [115]:
print(np.mean(data))

92.2

In [117]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [118]:
import pandas as pd

print(pd.__version__)

3.0.3

In [131]:
data={"name":["a","b","c"],"B":[4,5,6]}
df=pd.DataFrame(data)
print(df)
print(df[df['B']>=5])
print(df['B']>=5)

  name  B
0    a  4
1    b  5
2    c  6
  name  B
1    b  5
2    c  6
0    False
1     True
2     True
Name: B, dtype: bool

In [132]:
print(df['B']>=5)

0    False
1     True
2     True
Name: B, dtype: bool

In [135]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [20, 22, 19, 24, 21],
    "score": [88, 75, 93, 60, 85]
}

df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)
import pandas as pd
df=pd.read_csv("students.csv")
print(df)

      name  age  score
0    Alice   20     88
1      Bob   22     75
2  Charlie   19     93
3    David   24     60
4      Eva   21     85

In [ ]:
df.head(3)

      name  age  score
0    Alice   20     88
1      Bob   22     75
2  Charlie   19     93

In [142]:
df.describe()

             age      score
count   5.000000   5.000000
mean   21.200000  80.200000
std     1.923538  13.065221
min    19.000000  60.000000
25%    20.000000  75.000000
50%    21.000000  85.000000
75%    22.000000  88.000000
max    24.000000  93.000000

In [145]:
df.columns

Index(['name', 'age', 'score'], dtype='str')

In [146]:
df[df["score"]>80]

      name  age  score
0    Alice   20     88
2  Charlie   19     93
4      Eva   21     85

In [150]:
df["score"]
df[["score","name"]]

   score     name
0     88    Alice
1     75      Bob
2     93  Charlie
3     60    David
4     85      Eva

In [152]:
df[["age","score","name"]]

   age  score     name
0   20     88    Alice
1   22     75      Bob
2   19     93  Charlie
3   24     60    David
4   21     85      Eva

In [154]:
df.groupby("age")["score"].mean()

age
19    93.0
20    88.0
21    85.0
22    75.0
24    60.0
Name: score, dtype: float64

In [155]:
%pip install matplotlib.pyplot

ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
ERROR: No matching distribution found for matplotlib.pyplot
Note: you may need to restart the kernel to use updated packages.

In [156]:
import matplotlib.pyplot as plt

print(plt.__version__)

ModuleNotFoundError: No module named 'matplotlib'